// ============================================================
//  CONTENT.JS — edit your text here, not in index.html
// ============================================================

const CONTENT = {

  // ── HERO ────────────────────────────────────────────────
  'hero-eyebrow': 'CDEV 150 · MIDTERM REFLECTION · ANNA DANIELSON · MARCH 2026',
  'hero-intro': 'This project is framed as a mixtape. Music was the most reliable constant of my upbringing — sometimes the only thing that felt entirely mine. Each section opens with a song chosen as an epigraph, not as decoration, but because some things resist being said plainly. The first songs are ones my father loved. They drifted from the record player through all of my childhood, including the hours I spent at the kitchen table doing schoolwork. As the playlist moves forward, so does the internal dialogue I carried through adolescence — the slow accumulation of questions I didn\'t yet have language for. I\'ve included photographs of myself at different stages of my education as a reminder that underneath the theory and the retrospect is simply a kid trying to find her way.',

  // ── SECTION 1: STRUCTURE BEFORE SELF ────────────────────
  's1-label': '01 — STRUCTURE BEFORE SELF',
  's1-pullq': 'AN ANSWER KEY DETERMINED TRUTH.',
  's1-p1': 'I began my formal education not in a classroom but at a kitchen table in Hamilton, Ohio, with packets mailed from a correspondence school in Baltimore. The school provided textbooks, a structured curriculum, and a remote teacher to grade my work. It was, in many ways, a rigorous classical education — orderly, sequential, and placed a high focus on testing.',
  's1-p2': 'I was my parents\' oldest child and their first "experiment" in homeschooling, a role that came with unspoken expectations. My parents were evangelical Christians and conservative libertarians who believed, with deep conviction, that educating their children was both their moral right and their spiritual duty. The government had no place in that formation. Neither did public school. So I learned at home, and I learned early that having the "right" answer was incredibly important for the approval of my parents, and God.',
  's1-p3': 'The correspondence model rewarded precision. An answer key determined truth. One wrong answer felt like a failure — not just academic, but personal. Without peers to measure myself against, without the natural reassurance that other children also struggle, the answer key became my only mirror. I internalized its judgments completely. In the Bible, one of the ten commandments is to "honor thy father and mother." Being wrong meant I had also offended God.',
  's1-p4': 'Looking back through the lens of educational theory, what was missing in those early years becomes clear. Jean Piaget\'s theory of cognitive development holds that children construct knowledge actively, through interaction with their environment and the people in it (Piaget, 1952). But the correspondence model gave me knowledge as a finished product — pre-assembled, authoritative, and delivered by mail. There was no room for the kind of exploratory, hands-on learning Piaget described as essential to intellectual growth. I was not constructing understanding; I was receiving it.',
  's1-p5': 'Even more significantly, Lev Vygotsky\'s concept of the Zone of Proximal Development — the space between what a learner can do alone and what they can achieve with guidance — was left largely unoccupied (Vygotsky, 1978). Vygotsky argued that learning is most powerful when a more knowledgeable other (a teacher, a peer, a mentor) scaffolds a student just beyond their current capacity. My only "more knowledgeable other" was the answer key. If I got it wrong, I had failed. My mom would say: let\'s figure out why, let\'s try again together. And while she had the best intentions, she was not trained in teaching practices. Additionally, the dynamic was complicated and contentious because she wasn\'t only my teacher, she was also my mother. The stakes were high for both of us, and that contention interfered with my ability to learn.',
  's1-quote': 'Learning is most powerful when a more knowledgeable other scaffolds a student just beyond their current capacity — not delivering knowledge as a finished product, but building it together.',
  's1-cite':  '— Vygotsky, 1978; Piaget, 1952',
  's1-cap2':  'before the curriculum, there was this family',
  's1-cap3':  'dad &amp; me',

  // ── SONG BREAK 1: I CAN'T GET OVER IT ───────────────────
  'br1-why': 'This song was written the year I was born, and it has grown up alongside me — danced to in my family\'s living room, played live, blasted in teenage fury, used to loosen the grip of my religion. Now it\'s doing one more thing.<br><br>Piaget tells us that children construct knowledge through exploration. Vygotsky tells us they grow through relationships. I can name what I was denied. I can cite the theories. I can extend grace to my parents\' intentions. And still:<br><br><div style="text-align:center">I forgive you. I can\'t get over it.<br>They say that time heals every wound. I can\'t get over it.<br>I can face it. But can\'t erase it yet.<br><b>"I Can\'t Get Over It" — The 77\'s</b></div>',

  // ── SECTION 2: LONELINESS OF LEARNING ALONE ─────────────
  's2-label': '02 — THE LONELINESS OF LEARNING ALONE',
  's2-pullq': 'MY HOMESCHOOL EXPERIENCE: LONELY.',
  's2-p1': 'My two younger brothers were also homeschooled, but they were not my peers in the intellectual sense — we were not grappling with the same material, debating the same ideas, or struggling through the same problems together. For a brief period, we attended cooperative learning groups with other homeschool families, but my family\'s financial instability made it too expensive to participate. And so, for the most part, I learned on my own.',
  's2-p2': 'John Dewey\'s philosophy of education speaks directly to what this absence cost me. Dewey argued that learning is inherently social — that knowledge is not simply transmitted from teacher to student, but constructed through dialogue, collaboration, and shared inquiry (Dewey, 1916). As Dewey argued (as cited in McLeod, 2025), learning is both an individual and a collaborative endeavor. It is through the friction of exchanging ideas, through having our assumptions challenged by others, and challenging theirs, that is when understanding deepens and learning can be cemented.',
  's2-quote': 'Constructivism also highlights the social aspect of knowledge construction. Learning is both an individual and a collaborative endeavor. By sharing ideas, learners can challenge each other\'s assumptions and collectively build deeper understanding.',
  's2-cite':  '— McLeod, 2025',
  's2-p3': 'I had none of that friction. I existed within a self-reinforcing feedback loop. My curriculum presented its conclusions as absolute truth with a heavy religious bias. My parents, acting with genuine love and sincere conviction, affirmed those conclusions at home. There was no peer who might have said, that doesn\'t make sense to me, or I learned something different, or even simply why? Without diverse perspectives, my intellectual world was not expansive — it was intense and enclosed.',
  's2-p4': 'Constructivist theory, particularly as developed by Vygotsky (1978) and elaborated by later scholars, emphasizes that the social negotiation of meaning is not a supplement to learning but its very engine. When we explain our thinking to others, we are forced to organize it. When others push back, we are forced to refine it. When we hear different interpretations of the same material, we are forced to contend with complexity. I was denied all of this. My education encouraged me to think for myself, but it defined the boundaries of legitimate thought so narrowly, and surrounded me with so few other minds, that "thinking for myself" could only ever mean reaching the same conclusions.',
  's2-cap1': 'already finding her own way to listen',
  's2-cap2': 'little me',

  // ── SONG BREAK 2: KEEP ON ROCKIN' IN THE FREE WORLD ─────
  'br2-why': 'Neil Young targets the hollow rhetoric of American liberty — the "free world" that abandons people in its own streets and terrorizes people beyond its borders. Many of my parents\' educational choices were made in the name of freedom: freedom of religion, freedom from government. But freedom without the tools and resources to navigate it isn\'t liberty — it\'s just another kind of captivity. The song\'s fury is at a system that calls itself free while keeping its own people in chains. This section is about the grief of realizing I\'d been deceived — not just by the rhetoric, but by the very theories and structures that shaped my education.<br><br><div style="text-align:center"><em>"We got a thousand points of light<br>For the homeless man<br>We got a kinder, gentler machine gun hand"<br><b>"Rockin\' In the Free World" — Neil Young</b></em></div>',

  // ── SECTION 3: A BIBLICAL WORLDVIEW ─────────────────────
  's3-label': '03 — A BIBLICAL WORLDVIEW',
  's3-pullq': 'THE HARM WAS NOT ONLY FALSE ACADEMICS. IT WAS STRUCTURAL.',
  's3-p1': 'By fourth grade, the correspondence school had proven too rigid for me and my younger brother, and my mother made the shift to building her own curriculum. This is when our education became explicitly theological. For science, she chose Apologia — a curriculum whose mission statement leaves no ambiguity: "We believe that the Bible teaches that God created the heavens and the earth out of nothing in six days. We conclude that scientific evidence points to the earth being young."',
  's3-p2': 'With Apologia, my science education was not really science education. It was apologetics — the practice of defending a predetermined theological conclusion against all evidence to the contrary. The Big Bang Theory was not a framework to be examined but an absolute falsehood to be debunked. The story of Noah\'s Ark was not a biblical myth to be interpreted but a geological event to be proven using pseudoscience. Nearly a decade passed before I understood that what I\'d been taught wasn\'t really science — it was religious belief dressed in scientific language.',
  's3-p3': 'But the harm was not only being taught false information. It was structural — it shaped how I thought, not just what I thought. The result was a profoundly binary cognitive framework: sacred versus secular, truth versus deception, God\'s universe versus the "unsaved" world. This kind of thinking is well-described in developmental psychology as black-and-white or dichotomous thinking — a mode of reasoning that categorizes experience in absolutes and resists nuance or ambiguity. In children, some degree of this is developmentally normal. But an educational environment that actively cultivates and rewards it can cement what should be a passing stage into a lasting cognitive pattern. I have done significant work over the years to recognize and interrupt this pattern in myself, but it has affected my education, my mental health, and my relationships.',
  's3-p4': 'James Paul Gee\'s theory of Discourse is a helpful framework for me to understand what was happening from an educational point of view (Gee, 1989). Gee distinguishes between primary Discourses — the language, values, and ways of being we acquire in our early home environments — and secondary Discourses, the broader social and institutional identities we develop through school, work, and community participation. For me, evangelical Christianity and homeschooling were fused into a single, all-encompassing primary Discourse. They did not merely describe who I was at home; they defined who I was, period.',
  's3-quote': 'The result was a profoundly binary cognitive framework: sacred versus secular, truth versus deception, God\'s universe versus the "unsaved" world.',
  's3-cite':  '— from my reflection',
  's3-cap1':  'pajamas and headphones — already her own world',

  // ── SONG BREAK 3: JESUS FREAK ──────────────────────────────────
  'br3-why': 'This song was the soundtrack of my teenage identity. I called myself a Jesus Freak without irony — proud of it, defined by it. Being set apart from the world wasn\'t a burden; it was a purpose. It made me special.<br><br>That\'s how the framework worked: you were saved or you weren\'t. Truth or deception. Sacred or secular. The lines were clean, the stakes were eternal, and I knew exactly which side I was on.<br><br><div style="text-align:center"><em>Separated, I cut myself clean from a past that comes back in my darkest of dreams.<br>There ain\'t no disguising the truth.<br><b>"Jesus Freak" — DC Talk</b></em></div>',

  // ── SECTION 4: UNSCHOOLING & TOTAL FREEDOM ──────────────
  's4-label': '04 — UNSCHOOLING AND THE WEIGHT OF TOTAL FREEDOM',
  's4-pullq': 'THE WEIGHT OF FREEDOM.',
  's4-p1': 'By high school, my mother had cycled through several more curriculums — Ambleside Online, Charlotte Mason, various free digital resources — before arriving at unschooling. It is the most radical form of child-led, self-directed learning: no fixed curriculum, no mandatory assignments, no conventional testing. The child follows their own curiosity, on their own terms.',
  's4-p2': 'In theory, unschooling is a liberating model. And there were moments that felt genuinely free — reading whatever I wanted, following my curiosity wherever it led, writing papers on Lord of the Rings, teaching myself Tolkien\'s elvish, spending long hours with the history and geography I loved. But freedom is only liberating if you have the tools to use it. Zaretta Hammond (2015) argues that the goal of education is not simply to fill students with information, but to help them "learn how to learn" (p. 1). Without that foundation, she writes, a dependent learner cannot perform complex tasks "without continuous support" (Hammond, 2015, pp. 29–30). I was not yet a self-directed learner. My entire way of thinking had been shaped by a single Primary Discourse — what Gee (1989) describes as the language, values, and behaviors absorbed through home and family from birth, functioning as an "identity kit" (p. 18). Gee (1989) observes that "school-based secondary discourses conflict with the values and viewpoints" of children whose primary discourse is rooted in religious community (p. 24). I had not developed the Secondary Discourses that would allow me to move through new intellectual territory on my own terms. Unschooling assumed exactly the kind of learner I had not yet become, and without structure or scaffolding, the freedom didn\'t open things up — it left me adrift.',
  's4-quote': 'Here is the problem. On his own, a dependent learner is not able to do complex, school-oriented learning tasks such as synthesizing and analyzing informational text without continuous support.',
  's4-cite':  '— Hammond, 2015, pp. 29–30',
  's4-p3': 'Gee (1989) describes a Discourse as an "identity kit" — a complete package of ways of thinking, speaking, and acting that allows one to take on a recognizable role within a social group (p. 18). These kits are not developed in isolation; they require access to institutions and the communities within them. I did have influential secondary institutions — primarily church and youth group — but these were extensions of my Primary Discourse rather than departures from it. They reinforced the same values, the same ways of interpretation, the same worldview. It was music that first offered me something different. As a teenager I began developing my own musical taste, independent of my father\'s record player, and music became its own kind of identity kit — a space where I could try on new ways of feeling and being without having to explain or justify them. It also brought me into relationship with different kinds of people and ways of thinking. Gee (1989) notes that discourses "can call for one to accept values in conflict with other discourses one is a member of" (p. 19). Music was one of the places I felt that conflict first — and where I began to have language for a confusion that had no clear place to go.',
  's4-p4': 'As I neared 12th grade graduation, that confusion came to a head. I was paralyzed. I had been told my whole life that my purpose was to be a faithful Christian — to serve God, to serve my future husband, perhaps to go into mission work. Careers were barely discussed. College was an afterthought. And when the world suddenly seemed to require that I have a direction, I had almost no framework for imagining one. The anxiety I felt was not laziness or lack of ambition. It was the logical consequence of an education that had never asked me to imagine a future for myself beyond the walls of my faith.',

  // ── SONG BREAK 4: ZOMBIE ─────────────────────────────────
  'br4-why': 'I was thirteen when the towers fell. We were homeschooled, so we watched it live — all of it. The buildings. The people. And then the war after. I didn\'t understand why we were bombing people who hadn\'t done anything to us, and I didn\'t know where to put that.<br><br>The world had been clean: saved or unsaved, truth or deception, God\'s side or the world\'s. And then suddenly it wasn\'t. That confusion had nowhere to go. It just lived in my head.<br><br><div style="text-align:center"><em>In your head, in your head, they are fightin\'. We must be mistaken.<br><b>"Zombie" — The Cranberries</b></em></div>',

  // ── SECTION 5: WHAT WAS MISSING ─────────────────────────
  's5-label': '05 — WHAT WAS MISSING',
  's5-pullq': '"WHAT MY EXPERIENCE ILLUMINATES IS NOT THE FAILURE OF INDIVIDUAL PEOPLE."',
  's5-p1': 'What going back through my homeschool education has shown me is how quietly a curriculum, a theory, a policy — any structure, really — can shrink what the mind finds available to think at all. Homeschooling is not inherently the problem. Neither are my parents who choose it. The problem is the frameworks people carry into it — the ideological, religious, and political assumptions that determine what gets taught, what gets excluded, and whose version of knowledge counts as truth. Those frameworks are rarely chosen consciously. They are inherited, absorbed, passed down through exactly the kind of primary Discourses Gee (1989) describes — identities so total that the very act of questioning them can feel like self-betrayal.',
  's5-p2': 'And Dewey (1916), Piaget (1952), and Vygotsky (1978) each, in different ways, describe what those frameworks crowded out: the friction of other minds, the scaffolding of a knowledgeable guide, the understanding that knowledge is built in relationship — not received in isolation. I had the isolation. I was missing everything else.',
  's5-quote': 'Educational equity is a matter of asking who gets to shape what is taught, in whose image learning is designed, and which students are permitted to see themselves as full participants in the construction of knowledge.',
  's5-cite':  '— Gee, 1989; Dewey, 1916',
  's5-p3': 'The loneliness I felt as a student has become something I carry into every classroom I enter. I know what it feels like to be on the outside of a conversation everyone else seems fluent in. To carry an education that prepared you for one world and dropped you into another. To feel like the rules of learning were written for someone else. That knowledge doesn\'t make me a better teacher by itself — but it makes me a more clear-eyed one. The kind who knows that good intentions inside a broken framework are still a broken framework. The kind who will look for what the framework is doing to the child, not just what the teacher is trying to do for them.',
  's5-cap1': 'sitting alone in a crowd',

  // ── SONG BREAK 5: SEVENTY TIMES 7 ────────────────────────
  'br5-why': 'I chose this song because it gave sound to an anger I couldn\'t name. The song is about the betrayal of a best friend — specific, personal, pointed. Mine wasn\'t. I just knew something had failed me, something I had trusted completely, something I hadn\'t chosen. The target was blurry. The pain wasn\'t.<br><br><div style="text-align:center"><em>Back in school they never taught us what we needed to know<br>Like how to deal with despair, or someone breaking your heart<br>For twelve years I\'ve held it all together<br>But a night like this is begging to pull me apart<br><b>"Seventy Times 7" — Brand New</b></em></div>',

  // ── SECTION 6: AND WHAT REMAINS ─────────────────────────
  's6-label': '06 — AND WHAT REMAINS',
  's6-pullq': '"THESE ARE NOT ONLY PEDAGOGICAL QUESTIONS. THEY ARE POLITICAL ONES."',
  's6-p1': 'I used to think the gaps in my education were mine to overcome — deficits to quietly correct before anyone noticed. It took a long time to understand that they weren\'t personal failures. They were the logical outcome of a structure that was never designed to leave room for doubt, or divergence, or a self that didn\'t fit the plan.',
  's6-quote': 'We know that the best and most organic learning builds on what students already know. We need to see students — and have them see themselves — as capable learners who can learn and do anything.',
  's6-cite':  '— Turk, 2023',
  's6-p2': 'Turk\'s (2023) framing is useful perspective for me: that we need to see students — and have them see themselves — as capable learners. I spent years not seeing myself that way. Not because I lacked ability, but because no one had ever framed my learning as something I was building. It was something being done to me, or for me, or through me — but rarely with me.',
  's6-p3': 'What I want to build is something genuinely different from what I was given — a classroom where a student\'s questions or confusions are the starting point, not problems to be managed. Where learning is done with students, not to them or for them. I spent long enough on the outside of that to know exactly what it costs. What I want to make is a space where not-knowing feels safe, where students see themselves as active participants in their learning — and feel ownership in the classroom and over their education.',
  's6-p4': 'But none of this stays in the classroom. A pedagogy built on student agency, culturally responsive teaching, on questions as a starting point, on learning built with students rather than handed down to them — that is not a neutral choice. It is a challenge to structures that have long preferred compliance over curiosity. To teach this way is already a political act, and it asks something beyond good practice: it asks us to advocate. For students the system has failed. For the conditions that make this kind of teaching possible. For policies that would make it the rule rather than the exception. And that means all of us — teachers, researchers, policymakers — being willing to name what isn\'t working and push for something better.',
  's6-cap':  'running free — what every child deserves',
  's6-cap2': 'anna &amp; kevin at an outdoor concert',
  's6-cap3': 'anna &amp; rae at twin peaks',
  's6-cap4': 'anna &amp; rae at the marin headlands',

  // ── SONG BREAK 6: ANTHEMS FOR A SEVENTEEN YEAR OLD GIRL ─
  'br6-why': 'My best friend and I played this song when we left home at eighteen. We knew what we were — the ones who asked too many questions, wanted too much, didn\'t fit the mold. In our community, that made us the rotten ones. We spoiled the bunch.<br><br>It took years to understand that the not-fitting was never the problem. The mold was.<br><br><div style="text-align:center"><em>Used to be one of the rotten ones and I liked you for that.<br><b>"Anthems For a Seventeen Year-Old Girl" — Broken Social Scene</b></em></div>',

  // ── SECTION 7: FIN ──────────────────────────────────────
  's7-big-close':     'EDUCATION MUST CENTER POSSIBILITY, COMMUNITY, AND COLLECTIVE RESPONSIBILITY.',
  's7-big-close-sub': 'What I know now is that education is never neutral. Every curriculum makes a claim about who matters, what counts as knowledge, and whose future is worth imagining. I grew up inside a system that answered those questions very narrowly. I am still, in some ways, learning my way out.<br><br>But I am also here — in college for the second time, writing this, thinking through the structures that shaped me with tools I wasn\'t given at that kitchen table in Ohio. The questions I\'m asking now are ones I didn\'t know I was allowed to ask then. That feels like something worth naming.<br><br>I started this project with a mixtape because music was the first place the framework cracked — the first space where I encountered a self that didn\'t have to be explained or justified. I think that is, in the end, what good education does. It creates the conditions for a person to become someone they couldn\'t have predicted. I didn\'t get that early enough. But I know what it sounds like. And I know how to make room for it.',
  's7-outro-cap': 'my kids at the Oakland teachers strike rally — they are why i want to be in education',
  's7-byline':    'ANNA DANIELSON · CDEV 150 · PROF. REBEKAH AUSTIN · MARCH 2, 2026',

  // ── SONG BREAK 7: CAME OUT SWINGING ─────────────────────
  'br7-why': 'This is the end of the mixtape. Which means it\'s also the end of the analysis — the part where I stop pulling the framework apart and say what I actually think.<br><br>I didn\'t get the education I deserved. I\'m still working out what that cost me. But I also made it here — to this page, to these questions, to a version of myself that knows the difference between being taught and actually learning. That didn\'t happen in spite of everything. It happened through it.<br><br><div style="text-align:center"><em>I came out swinging from a South Philly basement,<br>Caked in stale beer and sweat, under half-lit fluorescents<br>And I spent the winter writing songs about getting better<br>And if I\'m being honest, I\'m getting there<br><b>"Came Out Swinging" — The Wonder Years</b></em></div>',

};

// ── Apply content to DOM ─────────────────────────────────
Object.entries(CONTENT).forEach(([id, html]) => {
  const el = document.getElementById(id);
  if (el) el.innerHTML = html;
});
